regione-piemonte/decsira

- backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/ListField.java
- backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/PropertiesFileQueryFormConfigProvider.java
- backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/QueryFormConfig.java
- backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/QueryFormField.java
- backend/src/test/java/it/geosolutions/csi/sira/backend/queryform/model/PropertiesFileQueryFormConfigProviderTest.java
- backend/src/test/resources/test-feature.properties
* Added `label` and `geometry` configuration properties, translated to `featureTypeNameLabel` and `geometricField` in JSON output.
* Renamed `idField` --> `valueId` and `labelField` --> `valueLabel` both in configuration file and JSON output.
> Implemented Query Form Config Service - evolution step 4

- assets/cardTemplate.config
- Modified the link text
- A temporary metadata id has been used because currently a relation between dataset and metadata does not exist yet.
> Modified the metadata link section text

- security/sec-iride/pom.xml
- security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityServiceConfig.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/Builder.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/IrideServerURLBuilder.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/ToStringReflectionBuilder.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/UrlValidatorFactory.java
- added the possibility to configure a "fallback" RoleService, to use when IRIDE does not retrieve any roles for a given username
- this may change in scope in future, as requirements get clearer
- added some configuration validation conditions, to have IrideRoleService fail its initialization as soon as any validation condition fails
> Add Fallback RoleService

- security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java
- at the present moment in development there's no need to inspect the ThreadLocal<Request> from Dispatcher
- therefore removing useless imports
> No need to inspect request

- security/sec-iride/LICENSE.txt
- security/sec-iride/pom.xml
- security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityProvider.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityServiceConfig.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/exception/IrideSecurityApplicationException.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/IrideIdentity.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/IrideIdentityTokenizer.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/IrideIdentityValidator.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/exception/IrideIdentityException.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/exception/IrideIdentityInvalidTokensException.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/exception/IrideIdentityMissingTokenException.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/exception/IrideIdentityTokenizationException.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/token/IrideIdentityToken.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/token/value/IrideIdentityInvalidTokenValue.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/token/value/IrideIdentityMissingTokenValue.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/identity/token/value/IrideIdentityTokenValue.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/Constants.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/Flag.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/IrideSecurityUtils.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/Builder.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/IrideServerURLBuilder.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/ToStringReflectionBuilder.java
- security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/UrlValidatorFactory.java
- security/sec-iride/src/test/java/org/geoserver/security/iride/IrideRoleServiceTest.java
- security/sec-iride/src/test/java/org/geoserver/security/iride/identity/AllTests.java
- security/sec-iride/src/test/java/org/geoserver/security/iride/identity/IrideIdentityTokenizerTest.java
- security/sec-iride/src/test/java/org/geoserver/security/iride/identity/IrideIdentityValidatorTest.java
- added GPL2 license information
- each Java source file opens with a GPL2 license header
- a LICENSE.txt file, with the bulk of GPL2 license information, has been added at the root level of the project
- minor additions to POM file: added scope elements, with "test" value, for unit-test related dependencies
> License Information

- security/pom.xml
- to keep sec-iride module building outside of the standard build lifecycle execution a Maven profile has been added, as a temporary workaround until sec-iride module _IRIDE WS dependencies_ will be publicly available... somewhere
> Keep sec-iride module building outside of the standard build lifecycle execution

- security/sec-iride/pom.xml
- add GPL2 license header at the beginning of Maven POM file
> POM GPL2 license header

- security/sec-iride/src/main/java/org/geoserver/security/iride/entity/IrideIdentity.java
The error detail message is enough to specify the cause behind the validation failure: omit printing the stacktrace.
> Lessen the verbosity level for Iride Digital Identity validation errors (issue #174)

- backend/gs_data_dir/security/auth/iride/config.xml
- backend/gs_data_dir/security/role/iride/config.xml
- backend/gs_data_dir/security/usergroup/iride/config.xml
- backend/pom.xml
#215 
- added configuration files for each security service involved in `sec-iride` plugin security services
- modified `Maven` `POM` to add build profiles, one for each execution environments:
- `demo`
- `produzione`
- to properly compile each configuration file as per execution environments
- everything packed in a convenient zip archive, simply named `gs_data_dir.zip`
> Add the configuration files used in the context of sec-iride plugin (issue #215)

- frontend/iride-services/LICENSE.txt
- frontend/iride-services/README.md
- frontend/iride-services/pom.xml
- frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/Constants.java
- frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceConstants.java
- frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceController.java
- frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/vo/IrideRoleVO.java
- frontend/iride-services/src/main/resources/applicationContext.xml
- frontend/iride-services/src/test/java/test/it/csi/sira/frontend/iride/controller/IrideServiceControllerTest.java
- frontend/iride-services/src/test/java/test/it/csi/sira/frontend/iride/controller/IrideServiceControllerTestContextLoader.java
- frontend/iride-services/src/test/java/test/org/springframework/test/context/support/MockWebContextLoader.java
- frontend/iride-services/src/test/java/test/org/springframework/test/context/support/package-info.java
- frontend/iride-services/src/test/resources/log4j.properties
- frontend/iride-services/src/test/resources/testContext.xml
- frontend/web/pom.xml
#257 
- `IRIDE` roles retrieval for Frontend component by using `IRIDE` service client
- a simple _Spring MVC REST_ action has been defined, relying on `IRIDE` service client to query the `IRIDE` service
- the action "answers" only when called by a `GET` method, with `IRIDE` _Digital Identity_ header defined
- with unit tests (and mocks)
> Iride roles retrieval for frontend component (issue #257)

- security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java
#263 
- in the context of `IRIDE` _Role Service_: there's no such concept as "_Admin Role_" with respect to `IRIDE`, therefore the operation has been simplified removing reference to `IrideIdentity` as well as its validation, keep using the _fallback_ `RoleService`, if any has been _configured_.
> Simplified Admin Role retrieval in the context of IRIDE Role Service (issue #263)

- pom.xml
#279 
added the missing reference to `iride-services` module
> Fix sira-root Maven modules list (issue #279)

- security/iride-service-client/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java
- security/iride-service-client/src/main/resources/iride/soap/request/findRuoliForPersonaInApplication.ftl
- security/iride-service-client/src/main/resources/iride/soap/request/findRuoliForPersonaInUseCase.ftl
- security/iride-service-client/src/main/resources/iride/soap/request/findUseCasesForPersonaInApplication.ftl
- security/iride-service-client/src/main/resources/iride/soap/request/getInfoPersonaInUseCase.ftl
- security/iride-service-client/src/main/resources/iride/soap/request/identificaUserPassword.ftl
- security/iride-service-client/src/main/resources/iride/soap/request/isIdentitaAutentica.ftl
- security/iride-service-client/src/main/resources/iride/soap/request/isPersonaAutorizzataInUseCase.ftl
- security/iride-service-client/src/main/resources/iride/soap/request/isPersonaInRuolo.ftl
- security/iride-service-client/src/main/resources/iride/soap/response/findRuoliForPersonaInApplication.xsl
- security/iride-service-client/src/main/resources/iride/soap/response/findRuoliForPersonaInUseCase.xsl
- security/iride-service-client/src/main/resources/iride/soap/response/findUseCasesForPersonaInApplication.xsl
- security/iride-service-client/src/main/resources/iride/soap/response/getInfoPersonaInUseCase.xsl
- security/iride-service-client/src/main/resources/iride/soap/response/getInfoPersonaInUseCaseReturn.xsl
- security/iride-service-client/src/main/resources/iride/soap/response/identificaUserPassword.xsl
- security/iride-service-client/src/main/resources/iride/soap/response/isIdentitaAutentica.xsl
- security/iride-service-client/src/main/resources/iride/soap/response/isPersonaAutorizzataInUseCase.xsl
- security/iride-service-client/src/main/resources/iride/soap/response/isPersonaInRuolo.xsl
#271 
Added license headers to non-Java files, such as XSL documents or FreeMarker Template files (.ftl)
> Added license headers to non-Java files (#issue 271)

- frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceConstants.java
- frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceController.java
- frontend/iride-services/src/test/java/test/it/csi/sira/frontend/iride/controller/IrideServiceControllerTest.java
#306 
- discarded the "`accept/json`" `HTTP` header in `Spring` `MVC` `REST` service dispatching configuration
> HTTP header in REST service (issue #306)

- geoserver/src/pom.xml
- geoserver/src/web/app/pom.xml
- geoserver/src/web/app/src/main/webapp/WEB-INF/web.xml
- pom.xml
Ho sostituito al gs-sira-accessmanager-1.0-SNAPSHOT.jar i 4 jar di iride sviluppati da Simone e ho modificato aggiungendo nel web.xml il riferimento a geowebcache directory.
> customizzazione con le librerie di iride

- geoserver/src/web/app/pom.xml
Adesso nella WEB-INF/lib di geoserver è stata aggiunta la dipendenza a gs-sira-accessmanager
> scommentata la dipendenza di accessManager

- frontend/assets/aua.json
- frontend/js/components/template/SchedaToPDF.jsx
PDF file name is configurable, to pass model value just add {{xml_path}}
i.e
"card": {
"pdfname": "AUA_{{/wfs:FeatureCollection/wfs:member/sira:AutorizzazioneUnicaAmbientale/sira:istanza/sira:IstanzaAutorizzativa/sira:nrProvvedimento/text()}}.pdf",
"template": {
"default": "assets/cardTemplate.jsxt",
"QGIS": "assets/cardTemplate.QGIS.jsxt"
}
> PDF file name is configurable in aua.json

- frontend/assets/stabilimento.json
- security/app-schema/hale/autorizzazione_AEA.halex
- security/app-schema/hale/autorizzazione_AEA.halex.alignment.xml
- security/app-schema/hale/autorizzazione_AEA.halex.styles.sld
- security/app-schema/xsd/sira_AEA.xsd
Sono stati rilasciati sia i file di configurazione json che il mapping Hale, attenzione che per non sovrascrivere lo schema xsd sipra_AEA.xsd ho inserito lo schema sira_AEA.xsd che è una configurazione intermedia per l'intero caso d'uso. Ho inserito anche lo script del db al cui interno c'è sia la struttura che i dati.
> aggiunta di file di configurazione

- frontend/assets/application/conoscenze_ambientali/css/skin-dataset.css
- frontend/assets/application/conoscenze_ambientali/css/skin-mappa.css
- frontend/assets/css/fullscreen.css
- frontend/assets/css/qgis.css
- frontend/assets/css/sira.css
- frontend/js/components/FeatureGrid.jsx
- frontend/js/components/SiraFeatureGrid.jsx
- frontend/js/containers/FullScreenPanel.jsx
As you perform filter, by default only first 3 rows are displayed which is not equal to the default row per page. The commit contains fix for row buffer to equal the default rows per page.
##Issue
Data grid displays only 3 rows of filtered results
Data grid displays the rows equal to default rows per page of filtered results
> #739: Filter row buffer issue fix

- frontend/assets/css/sira.css
This PR adds fix to the icons overlapping in query builder 
##Issue
#806  
The group and delete icon will not be superimposed.
> #806 - Query builder icons overlap fix

- frontend/assets/application/conoscenze_ambientali/css/skin-mappa.css
- frontend/assets/css/sira.css
- frontend/js/components/SideQueryPanel.jsx
- frontend/js/components/SiraQueryPanel.jsx
This PR adds commits to treat text field not as autocomplete and minor style changes as requested
##Issue
#813 
- Add group and condition icon position interchanged
- Textfield will be treated as non autocomplete field
> #813: Query build fields modified

- frontend/js/actions/siradec.js
- frontend/js/components/template/Card.jsx
- frontend/js/components/template/LinkScheda.jsx
- frontend/js/components/tree/TreeData.jsx
- frontend/js/reducers/siradec.js
- frontend/package.json
This PR fixes the Sira tree issue
##Issue
#845 
- Fix Sira feature grid loading when card template is loading
- Sira tree library fix
- Upon clicking the tree node, load card template as soon as the feature config is loaded 
> #845: SiraTree issue fix

- frontend/js/components/FeatureGrid.jsx
This PR adds commit to fix missing filter in query builder
##Issue
#850 
- Filter will be added in query builder for all field types
> #850: Query filter fix

- frontend/js/components/template/PreviewMap.jsx
This PR adds commits to show map with only background when feature has no geometry in the MappaScheda (Preview Map)
##Issue
#873 
- When feature has no geometry, the opening card will not crash and MappaScheda will be displayed with background and no zoom
> #873: MappaScheda when no geometry
