regione-piemonte/decsira

.travis.yml, js/containers/__tests__/Home-test.jsx, karma.conf.continuous-test.js, karma.conf.single-run.js, package.json, tests.webpack.js
* Added Karma configuration for single-run and continuous integration.
* Implemented simple unit test to prove infrastructure is working
Fixes #3
=> Added config for unit tests

.eslintignore, pom.xml, web/pom.xml
* Added `pom.xml` in root folder.
* Added `web` module to build WAR artifact.
=> Maven build configuration

backend/pom.xml, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/DateField.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/ListField.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/PropertiesFileQueryFormConfigProvider.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/QueryFormConfig.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/QueryFormConfigNotFoundException.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/QueryFormConfigProvider.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/QueryFormField.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/QueryFormFieldType.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/service/QueryFormConfigService.java, backend/src/main/resources/applicationContext.xml, backend/src/test/java/it/geosolutions/csi/sira/backend/queryform/model/PropertiesFileQueryFormConfigProviderTest.java, backend/src/test/resources/test-feature.properties, pom.xml, web/pom.xml, web/src/main/webapp/WEB-INF/applicationContext.xml, web/src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml, web/src/main/webapp/WEB-INF/web.xml
* Adds `backend` module for backend services
* Basic implementation of query form configuration service
=> Added backend module with basic QueryFormConfigService

js/components/SiraQueryPanel.jsx
Pull request for the issue #16
=> Improvements to the QueryBuilder and related components

js/components/SiraQueryPanel.jsx
This pull request to close the issue #17
=> Implement an optional filter for FilterField.

js/components/SiraQueryPanel.jsx
This pull request upgrades the sira project in order to allow the logic groups management for filter fields into the query form tool.
=> Adding logic groups for the query form tool

aua_remote.properties, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/ListField.java, backend/src/main/java/it/geosolutions/csi/sira/backend/queryform/model/QueryFormFieldType.java, backend/src/test/java/it/geosolutions/csi/sira/backend/queryform/model/PropertiesFileQueryFormConfigProviderTest.java, backend/src/test/resources/test-feature.properties
* Adds support for reading allowed values from remote service
=> QueryFormConfigService step 3 - support for remote value service

assets/cardTemplate.config, js/actions/__tests__/card-test.js, js/actions/card.js, js/app.jsx, js/components/template/Card.jsx, js/components/template/DetailTitle.jsx, js/components/template/TemplateSira.jsx, js/components/template/card.css, js/components/template/index.js, js/containers/Sira.jsx, js/reducers/__tests__/card-test.js, js/reducers/card.js, js/stores/store.js, js/test-resources/template-test.config, package.json
Caricamento template di file esempio cardTemplate.config in assets
Mergiare [pull request #447] (https://github.com/geosolutions-it/MapStore2/pull/447) in Mapstore2 prima di questa.
=> Added Scheda con Titolo dettagliato

js/components/SiraQueryPanel.jsx
Adding localized content to the query panel components.
=> Query panel localized

assets/cardTemplate.config, assets/css/sira.css, js/components/SiraQueryPanel.jsx, js/components/template/Card.jsx, js/components/template/DetailTitle.jsx, js/components/template/Section.jsx, js/components/template/card.css
- Style panel review (on CSS and some react components including the template config)
- Updated the MapStore2 revision
=> Style panel review and first spatial filter with other component updates

assets/cardTemplate.config, index.html, js/components/SiraMap.jsx, js/components/SiraQueryPanel.jsx, js/components/template/DetailTitle.jsx, js/stores/store.js
- Some updates for the SIRA application components
- Update the MapStore2 revision
=> More updates for the query form spatial filter

js/components/SiraQueryPanel.jsx
Improvements for closing issues: #41 , #40 , #39 , #38
=> Improvements for the spatial filter details tool

index.html, js/app.jsx
This pull request fixes a wrong behavior in IE about the Intl initialization.
=> Fixing Intl initialization for IE

security/pom.xml, security/src/main/java/it/geosolutions/geoserver/sira/security/config/Rule.java, security/src/test/java/it/geosolutions/geoserver/sira/security/config/ConfigTest.java
* removed parent reference in POM
* Rule filter defaults to INCLUDE
=> Removed parent and fixed rule filter default

assets/cardTemplate.config, assets/css/sira.css, js/actions/__tests__/card-test.js, js/actions/card.js, js/actions/queryform.js, js/app.jsx, js/components/template/Card.jsx, js/components/template/DetailTitle.jsx, js/containers/Sira.jsx, js/reducers/__tests__/card-test.js, js/reducers/card.js, js/reducers/queryform.js, js/test-resources/testWFSModel.xml, js/utils/TemplateUtils.js, package.json
- Template model from WFS
- Updated the mapstore2 revision
=> Improvements for the templating system

js/actions/__tests__/card-test.js, js/components/template/Card.jsx, js/components/template/Section.jsx
Small improvements to the Card template CSS and test cases.
=> Improving the details card CSS

assets/cardTemplate.config, assets/css/sira.css, js/components/SiraQueryPanel.jsx, js/components/template/Section.jsx
- Improving CSS and components layout (template and queryform)
- Updated the MapStore2 revision (filter composer, tests, component improvements)
=> Updates for template and filter composition

security/app-schema/aua.xml, security/app-schema/includedTypes.xml, security/db/create_tables.sql, security/db/create_views.sql, security/src/test/resources/xsd/sipra.xsd, security/wfs/aua_comune.xml, security/wfs/requests.txt, security/xsd/sipra.xsd
* Turned some denormalized *views* into denormalized *tables*
* Revised App-Schema mapping to limit feature chaining as much as possible
=> Revised App-Schema mapping and denormalized tables for performance

assets/featureGridConfigB.json, js/components/SiraFeatureGrid.jsx
Small fix provided for the feature grid columns composition in B profile.
=> Fixing the feature grid columns composition

assets/aua.json, assets/cardModelConfig.json, assets/featureGridConfigA.json, assets/featureGridConfigB.json, assets/queryFormConfig.json, js/app.jsx, js/components/SiraMap.jsx, js/containers/Sira.jsx, js/utils/TemplateUtils.js
- Improvements for WFS requests
- Provided some small fixes to the query for funcionalities
- Updated the MapStore 2 revision
=> Improving the wfs requests and provided some fixes

assets/cardModelConfig.json, assets/cardTemplateA.config, assets/cardTemplateB.config, assets/featureGridConfigA.json, assets/featureGridConfigB.json, js/components/SiraFeatureGrid.jsx, js/components/template/Cer.jsx, js/components/template/OperazioniRecupero.jsx, js/components/template/TipoRifiuti.jsx, js/containers/Sira.jsx, js/reducers/grid.js
- Differentiating the card template configuration between profiles
=> Card template profiling

assets/css/home.css, assets/css/sira.css, config.json, index.html, js/actions/card.js, js/actions/controls.js, js/app.jsx, js/components/SiraFeatureGrid.jsx, js/components/SiraMap.jsx, js/components/SiraQueryPanel.jsx, js/components/template/Card.jsx, js/components/template/DetailTitle.jsx, js/components/template/LabeledField.jsx, js/components/template/LinkScheda.jsx, js/components/template/PreviewMap.jsx, js/components/template/card.css, js/containers/App.jsx, js/containers/Home.jsx, js/containers/Sira.jsx, js/reducers/card.js, js/reducers/controls.js, js/stores/store.js, translations/data.en-US, translations/data.it-IT
- Enabled additional mapstore2 components and controls
- Update the sira viewer
- More updates : i18n, localized etc
- Fixing preview, adding scalebar and other controls
- CSS review
- More updates
- General review af the involved components and CSS
- Updated the MapStore2 revision
=> Enabled additional mapstore2 components, more updates and reviews

assets/aua.json, js/components/SiraMap.jsx, js/containers/Sira.jsx, js/reducers/queryform.js, js/stores/store.js
- Enabled more mapstore2 tools: Overview, Locate, Measurement
- Improvement for sorting the search fields in dropdown list
=> Enabling additional tool and search field sorted by config

assets/getFeatureInfoConfigA.json, assets/getFeatureInfoConfigB.json, assets/infoTemplateA.config, assets/infoTemplateB.config, config.json, js/actions/__tests__/card-test.js, js/actions/card.js, js/actions/mapInfo.js, js/components/SiraQueryPanel.jsx, js/components/identify/GetFeatureInfo.jsx, js/components/identify/GetFeatureInfoViewer.jsx, js/components/identify/viewers/GMLViewer.jsx, js/components/template/Card.jsx, js/components/template/SiraTable.jsx, js/components/template/index.js, js/containers/Sira.jsx, js/reducers/__tests__/card-test.js, js/reducers/card.js, js/reducers/mapInfo.js, js/stores/store.js
- Improved the getfeatureinfo viewer for managing the gml info format
- Small fixes for draggable panels
- Updated the MapStore2 revision with some fixes to the locate and measurement inititial state
=> Improvements for getfeatureinfo in gml format, fixed draggable panels

assets/infoTemplateA.config, assets/infoTemplateB.config, assets/topologyModelConfig.json, config.json, js/actions/featuregrid.js, js/actions/mapInfo.js, js/components/SiraMap.jsx, js/components/identify/GetFeatureInfo.jsx, js/components/identify/GetFeatureInfoViewer.jsx, js/components/identify/TopologyInfoViewer.jsx, js/components/template/PreviewMap.jsx, js/containers/Sira.jsx, js/reducers/featuregrid.js, js/reducers/mapInfo.js, js/stores/store.js, js/utils/TemplateUtils.js, web/src/main/resources/proxy.properties
- Added Topology tool
- Some updates and improvements for getfeatureinfo
- override for proxy.properties
- Update the mapstore2 revision
=> Adding topology tool

assets/application/conoscenze_ambientali/css/skin-mappa.css, assets/cardModelConfig.json, assets/cardTemplateA.config, assets/cardTemplateB.config, assets/featureGridConfigA.json, assets/featureGridConfigB.json, assets/impiantoAutorizzato.config, config.json, js/actions/__tests__/card-test.js, js/actions/card.js, js/actions/userprofile.js, js/components/template/AdempimentiAmbientali.jsx, js/components/template/AuthorizedObject.jsx, js/components/template/Card.jsx, js/components/template/DetailTitle.jsx, js/components/template/LabeledField.jsx, js/components/template/PreviewMap.jsx, js/components/template/__tests__/DetailTitle-test.jsx, js/components/template/index.js, js/containers/Sira.jsx, js/reducers/card.js, js/reducers/userprofile.js, js/stores/store.js, js/utils/TemplateUtils.js
Added drillup and drilldown functionality
=> Implementing drillup/drilldown functionality

assets/cardTemplateA.config, assets/cardTemplateB.config, assets/css/sira.css, assets/queryFormConfig.json, config.json, js/components/SiraFeatureGrid.jsx, js/components/template/Section.jsx, js/containers/Sira.jsx, tematiche.json, translations/data.it-IT
- Some i18n updates
- Some changes into the basic config both for map and components
- Added features count for the sira feature grid component
=> Some required changes

applicazioni.html, assets/application/conoscenze_ambientali/css/skin-interna.css, assets/aua.json, dataset.html, js/components/MapHeader.jsx, js/components/SiraMap.jsx, js/containers/Sira.jsx, localConfig.json, tematiche.json, translations/data.it-IT, web/pom.xml
- Updates for GUI components 
- Improvements and Fixes for layertree
- Updated the app config
- Updated the sira pom file and added a new profile for demo on it
- Updated the mapstore2 revision
=> Updates for gui components and layertree

security/pom.xml
Added missing Maven POM to refactored security submodule
=> security submodule missing POM

security/pom.xml
elenco dei sotto moduli del layer di sicurezza
=> sotto moduli del layer di sicurezza

security/app-schema/mappings/auaTables.xml, security/app-schema/mappings/auaViews.xml, security/app-schema/mappings/auaViewsV2.xml, security/app-schema/mappings/includedTypesTables.xml, security/app-schema/mappings/includedTypesViews.xml, security/app-schema/mappings/includedTypesViewsV2.xml
- Set "encode functions" option to "true" for all datastores
- Fixed includedTypesTables.xml mapping
=> Fixes and improvements to table-based app-schema mapping

assets/featureGridConfigA.json, assets/featureGridConfigB.json, config.json, js/components/SiraFeatureGrid.jsx, js/components/SiraMap.jsx, js/components/SiraQueryPanel.jsx, js/components/identify/TopologyInfoViewer.jsx, js/components/template/Card.jsx, js/reducers/grid.js, localConfig.json, tematiche.json, translations/data.en-US, translations/data.it-IT
- Fixes for zoom to the selected feature
- Improvements for enablif the query tool search also with only the spatial filter set
- Other changes for translations files, layer names, feature selections and so on as required
=> Improvements

security/sec-iride/pom.xml, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityServiceConfig.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/MultilineRecursiveToStringStyle.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/RecursiveToStringStyle.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/builder/ToStringReflectionBuilder.java, security/sec-iride/src/main/resources/GeoServerApplication.properties, security/sec-iride/src/main/resources/applicationContext.xml, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideRoleServiceTest.java
- Added some more meaningful information about the organization, and the developers
- Updated plugin versions used, and reviewed configuration
- Add a couple of dependencies:
- Apache commons-lang3
- Google Guava
=> Modified "GeoServer CSI-Piemonte Iride2 Plugin" Maven POM

assets/aua.json, js/components/SiraFeatureGrid.jsx
- Restored the tool panel 
- Fixed the zoom to feature
- Updated the MapStore2 revision
=> Reenabling the toolpanel in the featuregrid and fix zoom to feature

security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/Flag.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/UrlValidatorFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/validator/IdentitaIrideValidator.java, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideRoleServiceTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/IdentitaIrideValidatorTestCase.java
- added a check to tell apart IRIDE-like from non-IRIDE usernames
- this may change in scope in future, could be just a temporary check
- removed useless comment
=> Add identita iride validation

security/sec-iride/src/main/java/org/geoserver/security/iride/util/parser/IdentitaIrideToken.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/parser/IdentitaIrideTokenizer.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/parser/exception/ErrorDuringTokenizationException.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/parser/exception/IdentitaIrideTokenizerException.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/parser/exception/MissingIdentitaIrideTokenException.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/validator/IdentitaIrideValidator.java
- refactored Identita IRIDE validation to extract the tokenization procedure
- will come in handy for future parsing of the same information
=> Identita Iiride Validation refactoring

web/pom.xml
- a minor fix to property url.geoserver value for produzione profile
=> POM property fix

security/sec-iride/src/main/java/org/geoserver/security/iride/identity/IrideIdentityValidator.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/IrideSecurityUtils.java, security/sec-iride/src/test/java/org/geoserver/security/iride/AllTests.java, security/sec-iride/src/test/java/org/geoserver/security/iride/Utils.java, security/sec-iride/src/test/java/org/geoserver/security/iride/identity/IrideIdentityTokenizerTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/identity/IrideIdentityValidatorTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/IrideSecurityUtilsTest.java
- more unit tests for validation procedure
- added a main test suite
- minor corrections
=> Identita Iride validation tests

js/reducers/queryform.js
Small fix for the query form initial state in the siradec implementation.
=> Fixing the query form reset

security/sec-iride/src/main/java/org/geoserver/security/iride/identity/IrideIdentity.java, security/sec-iride/src/main/java/org/geoserver/security/iride/policy/IridePolicyEnforcerDelegate.java, security/sec-iride/src/main/java/org/geoserver/security/iride/policy/PolicyEnforcerBase.java, security/sec-iride/src/main/java/org/geoserver/security/iride/policy/PolicyEnforcerHelper.java, security/sec-iride/src/main/java/org/geoserver/security/iride/policy/impl/IridePolicyEnforcerDelegateImpl.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/Factory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/IrideRoleServiceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/template/TemplateEngine.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/template/exception/TemplateEngineException.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/template/impl/freemarker/FreeMarkerTemplateEngine.java, security/sec-iride/src/main/resources/applicationContext.xml, security/sec-iride/src/test/java/org/geoserver/security/iride/soap/request/iride/AbstractIrideSoapRequestTemplateCompilationTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/AbstractTemplateEngineTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/AllTests.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/FindRuoliForPersonaInUseCaseTemplateEngineTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/GetInfoPersonaInUseCaseTemplateEngineTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/IdentificaUserPasswordTemplateEngineTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/IsIdentitaAutenticaTemplateEngineTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/IsPersonaAutorizzataInUseCaseTemplateEngineTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/IsPersonaInRuoloTemplateEngineTest.java, security/sec-iride/src/test/resources/templateContext.xml, security/sec-iride/src/test/resources/testContext.xml
- added IRIDE Policy Enforcer interfaces
- work-in-progress
- added a simple template engine mechanism, used internally by Policy Enforcers to prepare IRIDE SOAP Requests
- with test units
=> Policy enforcer delegate and template engine

security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/template/freemarker/FreeMarkerConfigurationDefaultFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/template/freemarker/FreeMarkerConfigurationFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/template/freemarker/FreeMarkerConfigurationFactoryBean.java, security/sec-iride/src/main/resources/applicationContext.xml, security/sec-iride/src/test/resources/testContext.xml
- Spring factory bean to simplify FreeMarker Configuration initialization
- it's a singleton
=> Template engine FreeMarker configuration

security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/roleservice/IrideRoleServiceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/template/freemarker/FreeMarkerConfigurationDefaultFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/template/freemarker/FreeMarkerTemplateEngineFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/template/freemarker/FreeMarkerTemplateEngineFactoryBean.java, security/sec-iride/src/main/resources/applicationContext.xml, security/sec-iride/src/main/resources/iride/soap/request/findRuoliForPersonaInApplication.xml, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideRoleServiceTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/AllTests.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/FindRuoliForPersonaInApplicationTemplateEngineTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/template/FindUseCaseForPersonaInApplicationTemplateEngineTest.java
- introduced template engine usage for IrideRoleService.getRolesForUser IRIDE SOAP request compilation
- introduced some Factory classes to better manage dependencies injection between the various objects involved in IRIDE SOAP request compilation
- updated unit tests
=> Calling iride using FreeMarker templates and HttpClient

assets/css/sira.css, js/actions/siracatalog.js, js/appConfig.js, js/components/catalog/DefaultNode.jsx, js/components/catalog/Vista.jsx, js/plugins.js, js/plugins/SiraCatalog.jsx, js/reducers/siracatalog.js, localConfig.json
Prima implementazione, ancora da chiarire cosa devo cercare dalla barra di ricerca e come gestire aggiunta oggetti e temi alla mappa. (da dove recupero le info necessarie?)
=> Catalogo con oggetti e viste tematiche per sidepanel

SiraNoMap.html, assets/application/conoscenze_ambientali/css/skin-mappa.css, assets/cardTemplate.jsxt, assets/css/sira.css, js/actions/siradec.js, js/components/SideFeatureGrid.jsx, js/components/SideQueryPanel.jsx, js/components/template/Card.jsx, js/components/template/PreviewMap.jsx, js/containers/NoMap.jsx, js/containers/SidePanel.jsx, js/containers/Sira.jsx, js/reducers/SiraMapConfig.js, js/reducers/siradec.js, js/siranomap/app.jsx, js/siranomap/appConfig.js, js/stores/store.js, js/utils/SiraUtils.js
Per testare grid,query e card  utilizzare il seguente link: http://localhost:8081/SiraNoMap.html#B/
=> closes #144

security/pom.xml
- Restored security Maven submodule sec-iride build
=> sec-iride build

security/sec-iride/src/main/java/org/geoserver/security/iride/util/xml/transform/StringResult.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/xml/transform/XmlTransformer.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/xml/transform/AbstractXslProcessorTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/util/xml/transform/others/AbstractOthersXslProcessorTest.java
- issue #157
- added a couple of utility methods to ease handling Source/Result creation
=> XMLTransformer enhancements

security/sec-iride/src/main/java/org/geoserver/security/iride/IrideGeoServerUser.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideUserGroupService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/api/PolicyEnforcerBase.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/policy/IridePolicyManager.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/AbstractIrideSecurityServiceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/IrideRoleServiceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/IrideUserGroupServiceFactory.java, security/sec-iride/src/main/resources/applicationContext.xml, security/sec-iride/src/test/java/org/geoserver/security/iride/AllTests.java, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideRoleServiceTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideUserGroupServiceTest.java, security/sec-iride/src/test/resources/testContext.xml
#172 
- Added implementation for Iride-specialized UserGroupService
- added/modified Factory classes
- added Spring beans
- a specialized GeoServerUser class has been introduced, overriding parent toString() method mainly for logging purposes
- with Unit tests
=> Iride user group service completion (issue #172)

security/sec-iride/src/main/resources/iride/soap/response/findRuoliForPersonaInApplication.xsl, security/sec-iride/src/main/resources/iride/soap/response/findRuoliForPersonaInUseCase.xsl, security/sec-iride/src/main/resources/iride/soap/response/findUseCasesForPersonaInApplication.xsl, security/sec-iride/src/main/resources/iride/soap/response/identificaUserPassword.xsl, security/sec-iride/src/main/resources/iride/soap/response/isIdentitaAutentica.xsl, security/sec-iride/src/main/resources/iride/soap/response/isPersonaAutorizzataInUseCase.xsl, security/sec-iride/src/main/resources/iride/soap/response/isPersonaInRuolo.xsl, security/sec-iride/src/test/resources/iride/soap/response/findRuoliForPersonaInApplication.xml, security/sec-iride/src/test/resources/iride/soap/response/findRuoliForPersonaInUseCase.xml, security/sec-iride/src/test/resources/iride/soap/response/findUseCasesForPersonaInApplication.xml, security/sec-iride/src/test/resources/iride/soap/response/getInfoPersonaInUseCase.xml, security/sec-iride/src/test/resources/iride/soap/response/identificaUserPassword.xml, security/sec-iride/src/test/resources/iride/soap/response/isIdentitaAutentica.xml, security/sec-iride/src/test/resources/iride/soap/response/isPersonaAutorizzataInUseCase.xml, security/sec-iride/src/test/resources/iride/soap/response/isPersonaInRuolo.xml, security/sec-iride/src/test/resources/transformationIrideSoapResponseContext.xml
=> Update the XSLs for IRIDE policies response processing (issue #173)

security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideUserGroupService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/config/BaseIrideSecurityServiceConfig.java, security/sec-iride/src/main/java/org/geoserver/security/iride/config/IrideAuthenticationProviderConfig.java, security/sec-iride/src/main/java/org/geoserver/security/iride/config/IrideRoleServiceConfig.java, security/sec-iride/src/main/java/org/geoserver/security/iride/config/IrideUserGroupServiceConfig.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideRoleServiceTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideUserGroupServiceTest.java
=> IRIDE plugin configuration objects review (issue #184)

frontend/assets/css/qgis.css, frontend/js/components/FeatureGrid.jsx, frontend/js/components/QGisFeatureGrid.jsx, frontend/js/containers/QGis.jsx, frontend/js/containers/SidePanel.jsx, frontend/js/utils/SiraFilterUtils.js, frontend/list.html
Obbligatorio il profilo e featureTypeIds
http://localhost:8081/list.html?profile=B&featureTypeIds=aua.109_22,aua.110_22,aua.108_22,aua.111_22,aua.112_22
=> closes #195

security/sec-iride/src/main/java/org/geoserver/security/iride/IrideAuthenticationProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideGeoServerUser.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideUserGroupService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/authentication/IridePolicyAuthenticationProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/IrideServiceAware.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/api/PolicyEnforcerBase.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/policy/handler/IridePolicyRequestHandler.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/policy/handler/IridePolicyResponseHandler.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/AbstractFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/sax/SAXSourceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/AbstractIrideSecurityServiceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/AbstractIrideServiceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/IrideAuthenticationProviderFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/IridePolicyAuthenticationProviderFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/IrideRoleServiceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/security/IrideUserGroupServiceFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/xml/transform/XmlTransformerUtils.java, security/sec-iride/src/main/resources/applicationContext.xml, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideRoleServiceTest.java, security/sec-iride/src/test/java/org/geoserver/security/iride/IrideUserGroupServiceTest.java, security/sec-iride/src/test/resources/testContext.xml
=> Iride specialized Authentication Provider (issue #179)

frontend/js/reducers/SiraMapConfig.js, frontend/js/utils/SiraUtils.js, frontend/testLocalStorageLayers.html
http://localhost:8081/SiraNoMap.html#/B/
il passaggio dei paramteri per lo zoom avviene ora settandoli in localStorage
http://localhost:8081/testLocalStorageLayers.html#/B
La pagina aggiunge in localStorage Aua
=> closes #196

security/iride-entities/src/main/java/org/geoserver/security/iride/entity/IrideIdentity.java, security/iride-entities/src/main/java/org/geoserver/security/iride/entity/identity/IrideIdentityValidator.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideAuthenticationProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideRoleService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideSecurityProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/IrideUserGroupService.java, security/sec-iride/src/main/java/org/geoserver/security/iride/authentication/IridePolicyAuthenticationProvider.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/policy/IridePolicyManager.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/policy/IridePolicyRegistry.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/policy/handler/IridePolicyRequestHandler.java, security/sec-iride/src/main/java/org/geoserver/security/iride/service/policy/handler/IridePolicyResponseHandler.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/factory/xstream/XStreamFactory.java, security/sec-iride/src/main/java/org/geoserver/security/iride/util/xml/transform/XmlTransformerErrorHandler.java
#214 
- reviewed the logging levels of the log messages emitted by the various plugin parts
- reviewed as well some logging messages to make them more descriptive
=> Logging levels review (issue #214)

frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/business/MetadataManager.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/controller/MetadataController.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonPlatformNumbers.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/utils/Constants.java, frontend/metadata-services/src/main/resources/queries.xml
#223 
[Metadata services 1.1.pdf](https://github.com/geosolutions-it/csi-sira/files/594896/Metadata.services.1.1.pdf)
=> Added getPlatformNumbers method in metadata services module #223

frontend/assets/cardTemplate.QGIS.jsxt, frontend/assets/cardTemplate.jsxt, frontend/assets/impiantoAutorizzato.jsxt, frontend/js/components/template/LinkScheda.jsx, frontend/js/components/template/SiraTable.jsx, frontend/js/containers/QGis.jsx
LinkScheda, apre una scheda di dettaglio.
Se viene passato detailsTemplateConfigURL questo prevale come cardTemplate su quelle impostato nelle configurazione dell'oggetto.
Se viene passata featureType si caricano le configurazione per la featureType altrimenti si usano quelle della activeFeatureType.
se viene passato id, viene recuperata le feature dal server, altrimenti utilizza quella già caricata dalla scheda di dettaglio dove il link è utilizzato.
=> closes #205

frontend/metadata-services/pom.xml, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/business/MetadataManager.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/controller/MetadataController.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonAppCategory.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonInfoBox.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonMetaObject.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonPlatformNumbers.java
(issue #245)
Now the pojo to json conversion in made from the already configured jsonconverter (jackson).
=> Removed the gson library (issue #245)

frontend/metadata-services/src/main/resources/queries.xml
(issue #235)
Added distinct in the queries in metadata services that retrive metadata object and view to avoid returning duplicate metadata.
=> Added distinct in the queries in metadata services (issue #235)

frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonAppCategory.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonInfoBox.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonMetaObject.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/dto/JsonPlatformNumbers.java
(issue #251)
Replaced deprecated json annotation with @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL).
=> Replaced deprecated json annotation (issue #251)

security/iride-commons/src/main/java/org/geoserver/security/iride/util/xml/transform/ErrorHandlerUtils.java
#221 
Corrected [`SONAR`](www.sonarqube.org/) rules violations where suitable
=> Corrected SONAR violations (issue #221)

frontend/iride-services/pom.xml, frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceConstants.java, frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceController.java, frontend/iride-services/src/test/java/test/it/csi/sira/frontend/iride/controller/IrideServiceControllerTest.java
#277 
- reviewed the frontend component request mapping for `IRIDE` roles retrieval
- updated accordingly unit tests
=> Frontend component request mapping for IRIDE  roles retrieval (issue #277)

frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/business/MetadataManager.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/controller/MetadataController.java, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/utils/Constants.java, frontend/metadata-services/src/main/resources/applicationContext.xml, frontend/metadata-services/src/main/resources/logger.properties, frontend/web/src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml
(issue #283)
updated Constants.java
updated MetadataManager.java
updated MetadataController.java
updated application-context.xml
updated metadata-mvc-dispatcher.xml
removed logger.properties
=> updated metadata service logging system (issue #283)

frontend/web/src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml
#289 
- added the Spring MVC bean definition needed to cover IRIDE REST service
=> Fix Spring MVC dispatching configuration (issue #289)

security/iride-service-client/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java
#288 
- Completed `IRIDE` service client by implementing the remaining policies callings
=> Completed IRIDE service client implementation (issue #288)

frontend/js/actions/mosaictile.js, frontend/webpack.config.js, map.html
in webpack.config I added:
rewrite: rewriteUrl("/decsiraweb/services/metadata/getMosaico"),
=> add call to getMosaico (issue #281)

metadata-batch/src/main/resources/application-context.xml, metadata-batch/src/main/resources/spring-db-context.xml
=> added config.properties for db connection (issue #296)

frontend/web/src/main/resources/log4j.properties
(issue #305)
updated log4j.properties for metadata-services under csi-sira\frontend\web\src\main\resources
=> updated log4j.properties for metadata-services (issue #305)

geoserver/src/accessmanager/LICENSE.txt, geoserver/src/accessmanager/README.md, geoserver/src/accessmanager/pom.xml, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/HidingAccessLimits.java, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/MappingFeatureIteratorSecureFactory.java, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/SecuredMappingFeatureIterator.java, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/SiraAccessManager.java, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/config/Rule.java, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/config/SiraAccessManagerConfiguration.java, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/config/SiraAccessManagerConfigurator.java, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/util/FeatureUtils.java, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/util/package-info.java, security/sec-iride/pom.xml
#270 
AKA "The Rules Engine" 
- Reviewed Maven POM
- Added license and readme files
- Added license headers in Java source files
- Reviewed Java source files, with some preliminary refactoring
=> IRIDE Resource Access Manager (issue #270)

frontend/web/pom.xml
#309 
Fixed multiple transitive dependencies that got copied in `DECSIRA` `WAR`
- updated frontend/web module `Maven` `POM` accordingly
=> Fixed WAR duplicate dependencies (issue #309)

frontend/js/actions/platformnumbers.js, frontend/js/app.jsx, frontend/js/components/PlatformNumbers.jsx, frontend/js/containers/Home.jsx, frontend/js/reducers/mosaic.js, frontend/js/reducers/platformnumbers.js, frontend/web/src/main/resources/geostore-datasource-ovr.properties
I also committed  geostore-datasource-ovr.properties (added last row)
=> add service getplatformnumbers (issue #310)

frontend/iride-services/pom.xml, frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceController.java, frontend/iride-services/src/main/resources/application.properties, frontend/iride-services/src/main/resources/applicationContext.xml, frontend/iride-services/src/test/resources/application.properties, frontend/iride-services/src/test/resources/log4j.properties, security/iride-service-client/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java
#316 
Fixed IRIDE URL configuration filtering for Spring MVC REST service 
- as per deploy environment
=> Spring MVC REST service fix (issue #316)

frontend/iride-services/pom.xml, frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceController.java, frontend/iride-services/src/main/resources/application.properties, frontend/iride-services/src/main/resources/applicationContext.xml, frontend/iride-services/src/test/resources/application.properties, frontend/iride-services/src/test/resources/log4j.properties, security/iride-service-client/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java
Reverts geosolutions-it/csi-sira#319
=> Revert "Spring MVC REST service fix (issue #316)"

frontend/iride-services/pom.xml, frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceController.java, frontend/iride-services/src/main/resources/applicationContext.xml, frontend/iride-services/src/main/resources/irideprop.xml, frontend/iride-services/src/test/resources/application.properties, frontend/iride-services/src/test/resources/irideprop.xml, frontend/iride-services/src/test/resources/log4j.properties, frontend/iride-services/src/test/resources/testContext.xml, frontend/web/src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml, security/iride-service-client/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java
I changed the way of enhancing iride's url. I used a bean in mvc-dispatcher.
=> fix build in iride-services (issue #324)

frontend/iride-services/pom.xml, frontend/iride-services/src/main/java/it/csi/sira/frontend/iride/controller/IrideServiceController.java, frontend/iride-services/src/main/resources/applicationContext.xml, frontend/iride-services/src/main/resources/irideprop.xml, frontend/iride-services/src/test/resources/application.properties, frontend/iride-services/src/test/resources/irideprop.xml, frontend/iride-services/src/test/resources/log4j.properties, frontend/iride-services/src/test/resources/testContext.xml, frontend/web/src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml, security/iride-service-client/src/main/java/org/geoserver/security/iride/service/IrideServiceImpl.java
Reverts geosolutions-it/csi-sira#331
=> Revert "fix build in iride-services (issue #324)"

metadata-batch/src/main/java/it/csi/sira/backend/metadata/Main.java, metadata-batch/src/main/java/it/csi/sira/backend/metadata/business/MetadataManager.java
update moveOldMetadata() in MetadataManager class.
=> fixed a problem when are removed old metadata (issue #350)

geoserver/src/web/app/pom.xml, geoserver/src/web/app/src/assembly/distribution.xml
Ho creato il tar del geoserver secondo le direttive standard di csi per le installazioni in collaudo e produzione.
=> configurazione della UI di installazione del geoserver

frontend/assets/cardTemplate.QGIS.jsxt, frontend/assets/cardTemplate.jsxt, frontend/js/components/template/htmlpdf/SiraTable.jsx, frontend/js/utils/ExportScheda.js
=> Exploded dependent tables and adde box to section in pdf print

frontend/assets/cardTemplateStab.jsxt, frontend/assets/stabilimento.json, frontend/config.json, frontend/metadata-services/src/main/java/it/csi/sira/backend/metadata/integration/dao/impl/SipraMtdTCategoriaApplDAOImpl.java
Ho inserito solo i file di configurazione dentro frontend/assets tralasciando i file di configurazione del mapping di Hale che sono in progress per la prossima ricerca dei punti di emissione. Ho anche rilasciato un file dentro il metadata-service in cui mi hanno chiesto di aggiungere un ordinamento relativo ad un id.
=> prima versione della configurazione dello Stabilimento

frontend/js/components/GridCellDate.jsx, frontend/js/components/template/LabeledField.jsx, frontend/js/components/template/htmlpdf/LabeledField.jsx, frontend/js/components/template/htmlpdf/SiraTable.jsx, frontend/js/plugins/SiraCatalog.jsx
passe locale="de-De" to change locale in date format, defult it-IT
=> Add locale

frontend/js/actions/addmap.js, frontend/js/actions/cart.js, frontend/js/app.jsx, frontend/js/components/Cart.jsx, frontend/js/components/CartPanel.jsx, frontend/js/components/Header.jsx, frontend/js/components/LoginPanel.jsx, frontend/js/reducers/cart.js, frontend/translations/data.en-US, frontend/translations/data.it-IT
missing:
- remove layers & services
- go to map
- localStorage
=> added cart component (first version)

frontend/assets/application/conoscenze_ambientali/css/skin-dataset.css, frontend/js/components/SiraSearchBar.jsx, frontend/js/components/catalog/DefaultNodeDataset.jsx, frontend/js/components/catalog/Vista.jsx, frontend/js/components/catalog/VistaDataset.jsx, frontend/js/containers/Dataset.jsx, frontend/js/plugins/SiraCatalog.jsx
Added infoBox to dataset, objects and view, stripped description text, added metadatainfobox to map view.
=> closes #423

frontend/js/components/FeatureGrid.jsx, frontend/js/containers/QGis.jsx
Added infoBox to dataset, objects and view, stripped description text, added metadatainfobox to map view.
=> closes #424

frontend/assets/application/conoscenze_ambientali/css/skin-dataset.css, frontend/assets/css/fullscreen.css, frontend/js/appConfig.js, frontend/js/containers/Dataset.jsx, frontend/js/containers/FullScreenPanel.jsx
Aggiunta navigazione fullscreen per querybuilder featurgrid e detail.
Altre piccole modifiche di stile.
=> closes #425

frontend/assets/application/conoscenze_ambientali/css/skin-mappa.css, frontend/js/actions/siracatalog.js, frontend/js/actions/siradec.js, frontend/js/components/FeatureGrid.jsx, frontend/js/containers/Dataset.jsx, frontend/js/containers/FullScreenPanel.jsx, frontend/js/plugins/SiraCatalog.jsx, frontend/js/reducers/SiraMapConfig.js
3 commits
1 minor style fixes for sidequerypanel, sidefeaturegrid and fullscreenfeaturegrid
2 Added ad thematic view to map from dataset catalog capability
3 Added siraId to objects loaded from catalog (enable metadatainfobox )
=> Thematic view

frontend/assets/css/fullscreen.css, frontend/js/actions/siracatalog.js, frontend/js/components/SiraSearchBar.jsx, frontend/js/containers/Dataset.jsx, frontend/js/plugins/SiraCatalog.jsx, frontend/js/reducers/siracatalog.js
Fixed css
Fixed searchbare searchtext
=> Minor fixes

frontend/assets/aua.json, frontend/assets/cardTemplate.jsxt, frontend/assets/cardTemplatePuntiEmissione.jsxt, frontend/assets/puntiEmissioneAtmosfera.json, frontend/assets/stabilimento.json, frontend/config.json, frontend/localConfig.json, frontend/stabilimenti.json, frontend/tematiche.json
non aveva preso alcune modifiche e non riuscivo a fare la git pull origin master
=> Avanzamento punti emissione iss410

frontend/assets/application/conoscenze_ambientali/css/skin-home.css, frontend/assets/application/conoscenze_ambientali/css/skin-interna.css, frontend/assets/application/conoscenze_ambientali/css/skin-mappa.css, frontend/js/actions/addmap.js, frontend/js/containers/Dataset.jsx, frontend/js/containers/Home.jsx, frontend/js/containers/Sira.jsx, frontend/localConfig.json, frontend/map.html, frontend/translations/data.it-IT
- updated css (add document.body.className)
- add in cart siradec layers
- tooltip
- position of identify tool
- removed news from home page
=> bug fixing

geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/expression/ExpressionRuleEngine.java, geoserver/src/accessmanager/src/test/java/it/geosolutions/geoserver/sira/security/AllTests.java, geoserver/src/accessmanager/src/test/java/it/geosolutions/geoserver/sira/security/IrideSiraSecurityTest.java, geoserver/src/accessmanager/src/test/java/it/geosolutions/geoserver/sira/security/SiraInfoPersonaTest.java
Refactoring SpEL custom functions to have more expressive use of IRIDE-related informations in Rules
=> Refactoring SpEL custom functions

security/app-schema/mappings/decsiraogc_emissioni/puntoEmissione/includedTypes.xml, security/app-schema/mappings/decsiraogc_emissioni/puntoEmissione/puntoEmissione.appschema, security/app-schema/mappings/decsiraogc_scarichi/puntoScaricoIndustriale/includedTypes.xml, security/app-schema/mappings/decsiraogc_scarichi/puntoScaricoIndustriale/puntoScaricoIndustriale.appschema, security/app-schema/mappings/decsiraogc_scarichi/puntoScaricoUrbano/includedTypes.xml, security/app-schema/mappings/decsiraogc_scarichi/puntoScaricoUrbano/puntoScaricoUrbano.appschema, security/app-schema/mappings/decsiraogc_stabilimenti/stabilimento/includedTypes.xml, security/app-schema/mappings/decsiraogc_stabilimenti/stabilimento/stabilimento.appschema, security/app-schema/mappings/siraemissioni/includedTypes.xml, security/app-schema/mappings/siraemissioni/sipra_AEA.appschema, security/app-schema/pom.xml
Configurati i parametri per il datasource di tst e prod
=> parametrizzati i riferimenti del datasource per tst e prod

frontend/assets/cardTemplatePuntiScaricoIndustriale.jsxt, frontend/assets/puntiScaricoIndustriale.json
CDU dei Punti di Scarico Industriale
=> risolti bug sulla ricerca

frontend/assets/cardTemplateImpiantoRifiutiDiscaricaAIA208.jsxt, frontend/assets/cardTemplateImpiantoRifiutiGenerico.jsxt, frontend/assets/cardTemplateImpiantoRifiutiSmaltimAIA208.jsxt, frontend/assets/impiantoRifiutiDiscaricaAIA208.json, frontend/assets/impiantoRifiutiGenerico.json, frontend/assets/impiantoRifiutiSmaltimAIA208.json, frontend/assets/infoTemplateImpiantoRifiutiDiscaricaAIA208.jsxt, frontend/assets/infoTemplateImpiantoRifiutiGenerico.jsxt, frontend/assets/infoTemplateImpiantoRifiutiSmaltimAIA208.jsxt
Tre configurazioni da testare e da correggere
RifiutiDiscaricaAIA208
RifiutiGenerico
RifiutiSmaltimAIA208
=> rilascio parziale delle configurazione dei rifiuti

frontend/assets/infoTemplateControlliScarichiUrbani.jsxt, frontend/assets/scarichi.json, frontend/js/components/FeatureGrid.jsx, frontend/js/containers/Dataset.jsx
* fix errore identify (xpath parser error)
* pulsante dettaglio (i) nascosto per feature senza la definizione del dettaglio
* controllo di autorizzazione su pagina dataset (lista full screen)
* fix xpath per campi lista errati
=> Fix per scarichi urbani

frontend/assets/scarichi.json, frontend/js/components/FeatureGrid.jsx
* seleziona tutto visualizza risultati in mappa
* reset non voluto visibilità colonne
=> Altri fix per scarichi urbani

backend/gs_data_dir/security/sira-access-manager.xml, frontend/assets/infoTemplateMonitoraggioDatiDimensionali.jsxt, frontend/assets/monitoraggioDatiDimensionali.json, frontend/assets/scarichi.json
Nuova configurazione sui dati dimensionali del monitoraggio depuratori e corretto la configurazione sugli scarichi per l''anno campione' reperito da una tabella di decodifica
=> corretto anno campione, inserito altro cdu

frontend/assets/puntiScaricoUrbano.json
=> corretto il filtro sul comune

geoserver/src/accessmanager/pom.xml, geoserver/src/accessmanager/src/main/java/it/geosolutions/geoserver/sira/security/util/FeatureUtils.java, geoserver/src/accessmanager/src/main/resources/applicationContext.xml, geoserver/src/accessmanager/src/test/java/it/geosolutions/geoserver/sira/security/SiraSecurityTest.java, geoserver/src/pom.xml, geoserver/src/pom_official.xml, geoserver/src/web/app/pom.xml, geoserver/src/web/app/src/test/java/org/geoserver/filters/GZIPResponseStreamTest.java, geoserver/src/web/app/src/test/java/org/geoserver/wicket/test/WicketTestApplication.java, geoserver/src/web/pom.xml, security/iride-commons/pom.xml, security/iride-entities/pom.xml, security/iride-service-client/pom.xml, security/sec-iride/pom.xml
This pull request updates geoserver to 2.17.x and related dependecies in the following modules
- geoserver
- geoserver/access-manager
- security
=> Update geoserver to 2.17.x

frontend/assets/cardTemplateFaseProcedimentale.jsxt
per la fase procedurale della VIA
=> recupero geometria poligonale

frontend/assets/application/conoscenze_ambientali/css/skin-mappa.css, frontend/package.json
Integration of attribute filter of type list fix from Mapstore
##Issue
Attribute filter doesn't get applied when the type is of 'list'
Filter query string gets formulated when the attribute filter type is of list
As part of #739
=> Filter issue fix integration from Mapstore

frontend/assets/anagrafeSitiContaminati.json, frontend/assets/application/conoscenze_ambientali/css/skin-home.css, frontend/assets/application/conoscenze_ambientali/css/skin-mappa.css, frontend/assets/css/sira.css, frontend/js/components/SiraExporter.jsx, frontend/js/components/identify/GetFeatureInfo.jsx, frontend/js/components/identify/featuregrid/FeatureGrid.jsx, frontend/js/components/template/SiraTable.jsx, frontend/js/plugins.js, frontend/js/utils/ExporterUtils.js, frontend/localConfig.json, frontend/package.json
**Fixes for the following**
- #753 - Shapefile export doesn't work
- #752 - Query builder windows should be resizable
- #750 - CSS issues
- #749 - Remove menu from Search tool
- #751 - Identify behaviour is not the same as the previous version
- #755 - Detail panels subtables are missing columns descriptions
=> Regression fixes

frontend/js/components/toc/DefaultGroup.jsx, frontend/js/plugins/SiraCatalog.jsx, frontend/localConfig.json
This PR fixes the issue with zoom to all feature and 'Default' group creation on query 
##Issue
#773 #776 #775  
- Zoom to all features zoom to the correct extent for the project's CRS
- Default empty group doesn't get created on query search
- Translation added for Catalog
=> #773, #776 & #775: Zoom to all features and TOC empty node fix

frontend/assets/viaFaseProcedimentale.json
Updated multi layer selection filter attribute as per requirement
=> #763: Update attribute filter for MLS

frontend/assets/viaFaseProcedimentale.json, frontend/js/utils/SiraFilterUtils.js
This PR adds geometry type to MLS configuration
##Issue
#763 
The styling is based on the geometry type of MLS layers and not based on main feature's geometry type
=> #763: Add geomtry type to MLS config

frontend/assets/viaFaseProcedimentale.json
Geometry xpath update for viaFaseProcedimentale
=> Geometry xpath update for viaFaseProcedimentale

frontend/assets/viaFaseProcedimentale.json, frontend/js/actions/featuregrid.js, frontend/js/components/FeatureGrid.jsx, frontend/js/components/SideFeatureGrid.jsx, frontend/js/components/template/Card.jsx, frontend/js/components/toc/SiraLayer.jsx, frontend/js/containers/SidePanel.jsx, frontend/js/reducers/siraLayers.js, frontend/js/utils/SiraFilterUtils.js
This PR adds fix to incorrect geomtype on vector layer and other feedbacks requested
**Ref:**
https://github.com/geosolutions-it/csi-sira/issues/763#issuecomment-724661989
https://github.com/geosolutions-it/csi-sira/issues/763#issuecomment-726146348
##Issue
#763  #804 
https://github.com/geosolutions-it/csi-sira/issues/763#issuecomment-724661989
=> #763: Specific main attribute for each MLS layers

frontend/js/actions/featuregrid.js, frontend/js/components/FeatureGrid.jsx, frontend/js/components/MultiSelectLayer.jsx, frontend/js/components/SideFeatureGrid.jsx, frontend/js/components/template/Card.jsx
Disable MLS icon when no geometry
=> #804: Disable MLS icon when no geometry

frontend/js/components/template/PreviewMap.jsx, frontend/js/utils/ExportScheda.js
This PR has commits fixing card template issues
##Issue
#829 
- Print pdf title will wrap when lengthy
- Fixed zoom property fix for preview map
=> #829: Card template issues fix

frontend/js/components/GridCellDate.jsx
This PR adds commits to fix the date formatting issue in feature grid
##Issue
#848 
The date is displayed in correct format in the feature grid
=> #848: Date format in feature grid

frontend/assets/application/conoscenze_ambientali/css/skin-home.css, frontend/assets/application/conoscenze_ambientali/css/skin-interna.css, frontend/assets/css/home.css, frontend/js/components/Header.jsx
This PR adds commit to fix the styling of username menu
##Issue
#847  
- The username menu will be displayed as per the requirement
- When user is logged in, the user icon will be shown in green
=> #847: User name style fix

frontend/assets/application/conoscenze_ambientali/css/skin-mappa.css, frontend/js/actions/__tests__/card-test.js, frontend/js/actions/card.js, frontend/js/actions/siradec.js, frontend/js/components/Header.jsx, frontend/js/components/template/Card.jsx, frontend/js/components/template/card.css, frontend/js/components/tree/TreeData.jsx, frontend/js/reducers/card.js
This PR adds commits to enhance the card template component
##Issue
#845 
- A loader will be displayed when card template is fetched 
- Minor style fixes
=> #845: Card loader added

frontend/assets/css/home.css
This PR adds commit to fix user icon styling
##Issue
https://github.com/geosolutions-it/csi-sira/issues/847#issuecomment-789018948
- Use icon will stay in black color.
- User icon will have a green background when logged in and on hover (while logged in) background changes to light green 
=> #847: User icon style fix

frontend/js/components/QGisFeatureGrid.jsx, frontend/js/components/SideFeatureGrid.jsx, frontend/js/components/SideQueryPanel.jsx, frontend/js/containers/FullScreenPanel.jsx, frontend/js/containers/QGis.jsx
This PR adds commits to fix search failing on search after resetting the filter
##Issue
#849 
- Resetting the filter and performing a new search will not fail
=> #849: Reset filter fix

frontend/assets/css/fullscreen.css, frontend/js/components/QGisFeatureGrid.jsx, frontend/js/stores/qGisStore.js
This commit adds fix to list card style and Qgis featuregrid
##Issue
#875 
- Style fix on card font styles
- Qgis featuregrid store and prop missing fix
=> #875: Style fix for card in list page and qgis featuregrid fix

frontend/assets/bdnDistribuzioneFauna.json, frontend/assets/bdnDistribuzioneFlora.json, frontend/assets/cardTemplateBdnDistribuzioneFauna.jsxt, frontend/assets/cardTemplateBdnDistribuzioneFlora.jsxt, security/app-schema/hale/bdnGrigliaDistribuzioneFauna.halex.alignment.xml, security/app-schema/hale/bdnGrigliaDistribuzioneFauna.xsd, security/app-schema/hale/bdnGrigliaDistribuzioneFlora.halex.alignment.xml, security/app-schema/hale/bdnGrigliaDistribuzioneFlora.xsd
Solo le distribuzioni su griglia
=> modificati sia la struttura dati che le info da cui andare a leggere
